# Site settings
email: dvenkatsagar@gmail.com
author_name: Sagar DV
baseurl: ""
url: "https://dvenkatsagar.github.io"
google_analytics: "UA-70428717-1"
post_limit: 5

# Social usernames/URLs
twitter_username: dvenkatsagar
facebook_username: dvenkatsagar
git_username:  dvenkatsagar
linkedin_link: https://www.linkedin.com/in/dvenkatsagar
google_plus_link: https://plus.google.com/+SagarDwibhashyam
stackoverflow_link: https://www.stackoverflow.com/users/3228518/dvenkatsagar
disqus_account: dvenkatsagar-github

# Build settings
markdown: kramdown
kramdown:
  input: GFM
#redcarpet:
#  extensions: ["smart", "tables", "no_intra_emphasis", "fenced_code_blocks", "autolink", "strikethrough", "superscript", "with_toc_data"]
permalink: pretty
exclude: [vendor]
