# Site settings
email: dvenkatsagar@gmail.com
author_name: Sagar DV
baseurl: ""
url: "https://dvenkatsagar.github.io"
#google_analytics: ""
post_limit: 5

# Social usernames/URLs
twitter_username: "dvenkatsagar"
facebook_username: dvenkatsagar
git_username:  dvenkatsagar
linkedin_link: http://www.linkedin.com/dvenkatsagar
google_plus_link: "https://plus.google.com/+SagarDwibhashyam"
disqus_account: dvenkatsagar-github

# Build settings
markdown: redcarpet
redcarpet:
  extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "strikethrough", "superscript"]
permalink: pretty
exclude: [vendor]
